export const ADD_FUNCIONARIO = "ADD_FUNCIONARIO"
export const GET_FUNCIONARIO = "GET_FUNCIONARIO"
export const REMOVE_FUNCIONARIO = "REMOVE_FUNCIONARIO"
export const UPDATE_FUNCIONARIO = "UPDATE_FUNCIONARIO"
